run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-rules:
    # Ignore certain issues in test files
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
