version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  gosec:
    excludes:
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    # Ignore certain issues in test files
    - path: _test\.go
      linters:
        - errcheck
        - ineffassign
