version: 2

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

linters-settings:
  gosec:
    excludes:
      - G304 # File path provided as taint input

issues:
  exclude-rules:
    # Exclude G304 (file path) warnings for legitimate file operations
    - text: "G304: Potential file inclusion via variable"
      linters:
        - gosec

  max-same-issues: 3
  max-issues-per-linter: 10