# Temporal Clustering Configuration for Timeline2SVG
# Optimized for visualizing events that occur close in time
# Use with: timeline2svg --debug events.csv temporal-clustering-config.yaml

font:
  family: "Arial, sans-serif"
  size: 12

colors:
  background: "#ffffff"
  timeline: "#333333"
  events: "#4285f4"
  text: "#333333"
  notes: "#666666"

layout:
  width: 1200
  height: 600
  margin_top: 80
  margin_bottom: 80
  margin_left: 100
  margin_right: 100
  event_spacing: 120

timeline:
  line_width: 2
  show_dates: true
  show_times: true
  horizontal_buffer: 50
  avoid_text_overlap: true
  min_text_spacing: 10        # Low value enables time-proportional positioning
  min_callout_length: 40
  max_callout_length: 200     # High value allows constraint solver flexibility
  callout_levels: 8           # More levels = better clustering options
  text_element_padding: 1
  callout_text_gap: 5

event_marker:
  shape: "circle"
  size: 8
  fill_color: "#4285f4"
  stroke_color: "#333333"
  stroke_width: 2
